config/routes.rb
Rails.application.routes.draw do
  root 'index#index'

  get '/about_us', to: 'index#about_us', as: 'about_us'
  get '/top100', to: 'index#top_100', as: 'top_100'
  get 'how_to_bet', to: 'index#how_to_bet', as: 'how_to_bet'

  resources :users, only: [:new, :create]
  scope module: 'clearance', path: 'admin' do
    resource 'sessions', only: [:new, :create, :destroy]
  end

  scope path: 'admin' do
    resources 'matches', only: [:create, :update, :index]
    resources 'dashboards', only: [:index]
  end

  get '/betting', to: 'users#betting', as: 'betting'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flag.rb
class Flag < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :teams
end

app/models/match.rb
class Match < ApplicationRecord
  attr_reader :team
	belongs_to :team_1, :class_name => 'Team'
	belongs_to :team_2, :class_name => 'Team'

  scope :upcoming_matches, -> { where('time > ?', Time.now ).order('time ASC').limit(4)}

  def self.get_team_1_name
    self.team_1.name
  end
end

app/models/team.rb
class Team < ApplicationRecord
	belongs_to :group, optional: true
	has_many :matchs
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
	before_action :require_login
  layout 'admin_layout'

	private
	def sign_in_url
		admin_login_path
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/clearance/base_controller.rb
class Clearance::BaseController < ApplicationController
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :require_login
  layout 'admin_layout'
  def index
    @users = User.where(:admin => false)
    @matches = Match.all
    render 'admins/index'
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @flags = Flag.all
    @matches = Match.upcoming_matches
  end

  def how_to_bet

  end

  def about_us

  end

  def top_100

  end

  def how_to_bet

  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :require_login
  layout 'admin_layout'
  def index
    @upcoming_matches = Match.upcoming_matches
    render 'admins/match_setup'
  end

  def create

  end

  def update
    match_id = params[:match_id].to_i
    match = Match.find(match_id)
    team_1 = match.team_1.name
    team_2 = match.team_2.name
    description = params[:description] || "description"

    DongWorker.perform_async(match_id, team_1, team_2, description)
    # respond_to do |format|
    #   format.js { render :template => "admins/create_new_bet.js.erb", layout: false, content_type: 'text/javascript'  }
    # end
  end

  private
  def match_params
    params.permit(:match, :match_id, :description)
  end
end

app/controllers/users_controller.rb
require 'ethereum.rb'

class UsersController < ApplicationController
  def new
    @user = User.new
    render "users/register"
  end

  def create
    email = params[:user][:email]
    nickname = params[:user][:nickname]
    pk = params[:user][:private_key]
    amount = params[:user][:amount].to_i
    wallet_address = params[:user][:wallet_address]

    # config = Rails.application.config_for(:blockchain)
    # client = Ethereum::Client.create(config['rpc_url'])
    # formatter = Ethereum::Formatter.new
    # @wallet_address = formatter.to_address(params[:user][:wallet_address])

    # from = formatter.to_address(config['address'])
    # to = formatter.to_address(user_params[:wallet_address])

    # value = client.int_to_hex(formatter.to_wei(2))
    # client.eth_send_transaction(from: from, to: to, value: value)
    # path = File.join(Rails.root, "build/contracts/WCC.json")
    # contract_json = File.read(path)
    # contract = JSON.parse(contract_json)

    # @contract = Ethereum::Contract.create(
    #   name: 'WCC',
    #   address: '0xea6b7373e88d075809000e45cb4a417ee1c5616a',
    #   abi: contract['abi'],
    #   client: client
    # )
    # tx = @contract.transact.transfer(@wallet_address,  @amount)


    # puts Time.now
    HardWorker.perform_async(nickname, email, pk, amount, wallet_address)

    # loop do
    #   raise Timeout::Error if ((Time.now - start_time) > 5.minutes)
    #   break unless client.eth_get_transaction_by_hash(tx.id).try(:dig, 'result', 'blockNumber').nil?
    #   sleep 2.seconds
    # end
    # UserMailer.with(user: @nickname, mail: @email, private_key: @pk).welcome_email.deliver_later

    # puts Time.now
    # byebug
    # @user = User.new(:nickname => @nickname, :email => @email, :private_key => @pk, :wallet_address => @wallet_address, :password => "1", :amount => @amount)
    # if @user.save
    #   UserMailer.with(user: @nickname, mail: @email, private_key: @pk).welcome_email.deliver_later
    # respond_to do |format|
    #   format.js
    # end
    # else
    #   puts "fail"
    # end
  end

  def betting

  end

  private

  def user_params
    params.require(:user).permit(:email, :nickname, :private_key, :wallet_address, :amount)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/create_new_bet.js.erb
alert ('Match ID = ' + <%= @match.id %>);
alert ('Find me in AdminsController and views/admins/create_new_bet');

app/views/admins/index.html.erb
<span class="page-title" data-content="index" ></span>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <div class="row">
      <ol class="breadcrumb">
        <li><a href="#">
          <em class="fa fa-home"></em>
        </a></li>
        <li class="active">Dashboard</li>
      </ol>
    </div>
      <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
      </div>
    </div><!--/.row-->

    <div class="panel panel-container">
      <div class="row">
        <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
          <div class="panel panel-teal panel-widget border-right">
            <div class="row no-padding"><em class="fa fa-xl fa-shopping-cart color-blue"></em>
              <div class="large"><%= @matches.count %></div>
              <div class="text-muted">Matches</div>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
          <div class="panel panel-blue panel-widget border-right">
            <div class="row no-padding"><em class="fa fa-xl fa-comments color-orange"></em>
              <div class="large"><%= @users.count %></div>
              <div class="text-muted">Users</div>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
          <div class="panel panel-orange panel-widget border-right">
            <div class="row no-padding"><em class="fa fa-xl fa-users color-teal"></em>
              <div class="large"><%= @users.count %></div>
              <div class="text-muted">Users</div>
            </div>
          </div>
        </div>
        <div class="col-xs-6 col-md-3 col-lg-3 no-padding">
          <div class="panel panel-red panel-widget ">
            <div class="row no-padding"><em class="fa fa-xl fa-search color-red"></em>
              <div class="large">25.2k</div>
              <div class="text-muted">Page Views</div>
            </div>
          </div>
        </div>
      </div><!--/.row-->
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-default articles">

        <div class="panel-heading">
            Upcoming Maches
            <!-- <ul class="pull-right panel-settings panel-button-tab-right">
              <li class="dropdown"><a class="pull-right dropdown-toggle" data-toggle="dropdown" href="#">
                <em class="fa fa-cogs"></em>
              </a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li>
                    <ul class="dropdown-settings">
                      <li><a href="#">
                        <em class="fa fa-cog"></em> Settings 1
                      </a></li>
                      <li class="divider"></li>
                      <li><a href="#">
                        <em class="fa fa-cog"></em> Settings 2
                      </a></li>
                      <li class="divider"></li>
                      <li><a href="#">
                        <em class="fa fa-cog"></em> Settings 3
                      </a></li>
                    </ul>
                  </li>
                </ul>
              </li>
            </ul> -->
            <!-- <span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span> -->
          </div>
          <div class="panel-body articles-container">

            <div class="article border-bottom">
              <div class="col-xs-12">
                <div class="row">
                  <div class="col-xs-2 col-md-2 date">
                    <div class="large">30</div>
                    <div class="text-muted">Jun</div>
                  </div>
                  <div class="col-xs-10 col-md-10">
                    <h4><a href="#">Lorem ipsum dolor sit amet</a></h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at sodales nisl. Donec malesuada orci ornare risus finibus feugiat.</p>
                  </div>
                </div>
              </div>
              <div class="clear"></div>
            </div><!--End .article-->


          </div>

        </div>
      </div>
    </div>

    </div>
  </div>

app/views/admins/match_setup.html.erb
<span class="page-title" data-content="setup" ></span>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="#">
        <em class="fa fa-home"></em>
      </a></li>
      <li class="active">Match Setup</li>
    </ol>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Match Setup</h1>
    </div>
  </div><!--/.row-->

  <div class="row">
      <div class="col-md-6">
        <div class="panel panel-default articles">

        <div class="panel-heading">
            Upcoming Matches
            <!-- <ul class="pull-right panel-settings panel-button-tab-right">
              <li class="dropdown"><a class="pull-right dropdown-toggle" data-toggle="dropdown" href="#">
                <em class="fa fa-cogs"></em>
              </a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li>
                    <ul class="dropdown-settings">
                      <li><a href="#">
                        <em class="fa fa-cog"></em> Settings 1
                      </a></li>
                      <li class="divider"></li>
                      <li><a href="#">
                        <em class="fa fa-cog"></em> Settings 2
                      </a></li>
                      <li class="divider"></li>
                      <li><a href="#">
                        <em class="fa fa-cog"></em> Settings 3
                      </a></li>
                    </ul>
                  </li>
                </ul>
              </li>
            </ul> -->
            <!-- <span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-toggle-up"></em></span> -->
          </div>
          <div class="panel-body articles-container">
            <% @upcoming_matches.each do |match|  %>
            <div class="article border-bottom">
              <div class="col-xs-12">
                <div class="row">
                  <div class="col-xs-2 col-md-2 date">
                    <div class="large"><%=  match.time.strftime("%d") %></div>
                    <div class="text-muted"><%=  match.time.strftime("%B") %></div>
                  </div>
                  <div class="col-xs-10 col-md-10">
                    <h4><a class="upcoming_match" id="<%= match.id %>" data-name="<%= match.team_1.name %> vs <%= match.team_2.name %>"><%= match.team_1.name %> vs <%= match.team_2.name %></a></h4>
                    <p><%= match.description %></p>
                  </div>
                </div>
              </div>
              <div class="clear"></div>
            </div><!--End .article-->
            <% end %>
          </div>

        </div>
      </div>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            Create new bet contract
          </div>
          <div class="panel-body">
            <%= form_tag match_path(:match_id), method: :put, remote: 'true', :class => 'form-horizontal' do  %>
              <%= hidden_field_tag :match_id, nil, :id => "match_id" %>
              <div class="form-group">
                <%= label_tag 'Match', nil ,:class => "col-md-3 control-label" %>
                <div class="col-md-9">
                <%= text_field_tag :match, nil ,:class => "form-control", :id => "match_name"  %>
                </div>
              </div>
              <div class="form-group">
                <%= label_tag 'Description', nil ,:class => "col-md-3 control-label" %>
                <div class="col-md-9">
                <%= text_area_tag :description, nil ,:class => "form-control" %>
                </div>
              </div>
              <div class="form-group">
                  <div class="col-md-12 widget-right">
              <%= submit_tag "Submit", class: "btn btn-default btn-md pull-right" %>
            </div>
          </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>

</div>

app/views/index/about_us.html.erb
about us

app/views/index/how_to_bet.html.erb
<div class="container">
     <div class="row">
        <!--What is World Cup betting--> 
        <h1 class="lead text-center" style="font-size: 36px">What is World Cup Betting ?</h1>
        <div class="row" style="max-width:800px; margin: auto">  
             <p>
               WC Betting is a soccer betting site with ethereum-based platforms.
Our platform use token called WCC (WC Coin). Player who want to bet must buy our token to start betting and win.
            </p>
        </div>
     </div>
     <div class="row">
        <!--Rules-->
        <h1 class="lead text-center" style="font-size: 36px">Rules</h1>
        <div class="row" style="max-width:800px; margin: auto">
            <p>
            Each player will have to choose a team that he/she thinks could win the match and place at least a number of tokens depending on each match.
After the match is over, player who bet the winner team will be returned their original bets + tokens which are divided equally from the total tokens of the losing ones. 
            </p>
        </div>
     </div>
        <!--Getting started-->
        <h1 class="lead text-center" style="font-size: 36px">Getting started</h1>
        <div class="row" style="max-width:800px; margin: auto">
                 <h3 style="margin-bottom: 30px">Install and log in Metamask</h3>
                 <p>Metamask is available for Chrome, Opera, Firefox, you can download it from here: <a href="https://metamask.io/">Metamask</a></p>
                 <iframe width="853" height="480" src="https://www.youtube.com/embed/6Gf_kRE4MJU" frameborder="0" allowfullscreen=""></iframe>
        </div>
        <div class="row" style="max-width:800px; margin: auto">
                 <h3 style="margin-bottom: 30px">Send Ether to your wallet</h3>
                 <p>Since our website is based on Ethereum, you must have Ether (ETH) in your wallet to make purchase tokens and betting. ETH can be purchased directly from Metamask or from other exchanges, for example: Coinbase, Coinmama or BitPanda etc.. If this is the first time you buy Ether, we recommend you to buy from <a href="https://buy.coinbase.com/">Coinbase.</a></p>
        </div>
        <div class="row" style="max-width:800px; margin: auto">
                 <h3 style="margin-bottom: 30px">Get token</h3>
                 <p>Players must have Token to play. Click <a href="<%= new_user_path %>"><i class="fa fa-sign-in" aria-hidden="true"></i> Claim Your Token</a> on the righ top of the menu</p>
                 <p>Enter email, nickname and amount of WCC you want to get and click "Claim".</p>
                 <p>We will send to your email a token address so please check your inbox. If you can't find the email, check your junk box instead.</p>
                 <p>Open Metamask and click "Add token"</p>
                 <%= image_tag "BuyToken.png", style: "margin: 0px 0px 20px 0px"%>                  
                 <p>Paste the token address which we've sent to your mail box and click next</p>
                 <p>And tadaa, you are all set! Time to bet and win</p>
                 <%= image_tag "TokenBuySuccess.png", style: "margin: 0px 0px 20px 0px"%>                  
        </div>
        <div class="row" style="max-width:800px; margin: auto">
                <h3>Start betting</h3>
                <p>Select a match that is in OPEN mode, select the team you expect to win and the amount of token (WC Coin) you want to bet and press confirm.  Metamask will automatically deduct your existing coins.</p>
        </div>
        <div class="row" style="max-width:800px; margin: auto">
                <h3>After match</h3>

        </div>
</div>

app/views/index/top_100.html.erb
Top 100

app/views/layouts/_admin_header.html.erb
 <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse"><span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span></button>
        <a class="navbar-brand" href="<%= dashboards_path %>"><span>WCCoin</span>Admin</a>
        <ul class="nav navbar-top-links navbar-right">
<!--
          <li class="dropdown"><a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
            <em class="fa fa-bell"></em><span class="label label-info">5</span>
          </a> -->
          <!-- <ul class="dropdown-menu dropdown-alerts">
            <li><a href="#">
              <div><em class="fa fa-envelope"></em> 1 New Message
                <span class="pull-right text-muted small">3 mins ago</span></div>
              </a></li>
              <li class="divider"></li>
              <li><a href="#">
                <div><em class="fa fa-heart"></em> 12 New Likes
                  <span class="pull-right text-muted small">4 mins ago</span></div>
                </a></li>
                <li class="divider"></li>
                <li><a href="#">
                  <div><em class="fa fa-user"></em> 5 New Followers
                    <span class="pull-right text-muted small">4 mins ago</span></div>
                  </a></li>
                </ul> -->
              </li>
            </ul>
          </div>
        </div><!-- /.container-fluid -->
      </nav>

<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
    <div class="profile-sidebar">
      <div class="profile-userpic">
        <%= image_tag "logo.png", class: 'img-responsive' %>
      </div>
      <div class="profile-usertitle">
        <div class="profile-usertitle-name">WCC</div>
        <div class="profile-usertitle-status"><span class="indicator label-success"></span><%= current_user.nickname %></div>
      </div>
      <div class="clear"></div>
    </div>
    <div class="divider"></div>
    <ul class="nav menu">
      <li class="active" id="index"><a href="<%= dashboards_path %>"><em class="fa fa-dashboard">&nbsp;</em> Dashboard</a></li>
      <li id="setup"><a href="<%= matches_path %>" id="setup" ><em class="fa fa-calendar">&nbsp;</em> Match Setup</a></li>
      <!-- <li><a href="charts.html"><em class="fa fa-bar-chart">&nbsp;</em> Charts</a></li>
      <li><a href="elements.html"><em class="fa fa-toggle-off">&nbsp;</em> UI Elements</a></li>
      <li><a href="panels.html"><em class="fa fa-clone">&nbsp;</em> Alerts &amp; Panels</a></li>
      <li class="parent "><a data-toggle="collapse" href="#sub-item-1">
        <em class="fa fa-navicon">&nbsp;</em> Multilevel <span data-toggle="collapse" href="#sub-item-1" class="icon pull-right"><em class="fa fa-plus"></em></span>
        </a>
        <ul class="children collapse" id="sub-item-1">
          <li><a class="" href="#">
            <span class="fa fa-arrow-right">&nbsp;</span> Sub Item 1
          </a></li>
          <li><a class="" href="#">
            <span class="fa fa-arrow-right">&nbsp;</span> Sub Item 2
          </a></li>
          <li><a class="" href="#">
            <span class="fa fa-arrow-right">&nbsp;</span> Sub Item 3
          </a></li>
        </ul>
      </li> -->
      <li>
        <%= link_to sessions_path, method: 'delete' do %>
          <em class="fa fa-power-off">&nbsp;</em>Logout
        <% end %>
      </li>

    </ul>
  </div><!--/.sidebar-->

app/views/layouts/_footer.html.erb
<footer id="footer-section" class="footer-section">
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <h4 class="footer-title">about us</h4>
          <div class="about-widget">
            <p>World cup betting platform based on Ethereum Technology</p>
            <p class="margin-remove">Copyright (C) 2018 by Fetch Technologies</p>
          </div>
        </div>
        <div class="col-md-3">
           </div>
           
        <div class="col-md-3">
          <h4 class="footer-title">Useful Links</h4>
          <ul class="sitemap-widget">
            <li class="active"><a href="about.html">Home</a></li>
            <li><a href="about.html">About us</a></li>
            <li><a href="point-table.html">How to bet</a></li> 
            <li><a href="world-cup.html">Top 100</a></li> 
          </ul>
        </div>
        <div class="col-md-3">
          <!-- <h4 class="footer-title">newsletter</h4>
          <form class="footer-subscribe">
            <input type="text" class="form-input" placeholder="Name">
            <input type="email" class="form-input" placeholder="Email">
            <input type="submit" class="form-input" value="Send">
          </form> -->
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="header-top-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
          <div class="header-top-left">
            <ul>
              <li><a href="mailto:wccoin.test@gmail.com"><i class="fa fa-envelope-o" aria-hidden="true"></i> wccoin.test@gmail.com</a></li>
              <li><%= image_tag("american_flag.png") %>
                <a >English
                  <!-- <i class="fa fa-angle-down" aria-hidden="true"></i> -->
                </a>
                <!-- <ul>
                  <li><%= image_tag("vietnam_flag.png") %><a href="#">Vietnamese</a></li>
                </ul> -->
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
          <div class="social-media-area">
            <nav>
              <ul>
                <li><a href="index.html#" class="active"><i class="fa fa-facebook"></i></a></li>
                <li class="log"><a href="<%= new_user_path %>"><i class="fa fa-sign-in" aria-hidden="true"></i> Claim Your Token</a></li>
                <!-- </ul> -->
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="header-middle-area menu-sticky">
    <div class="container">
      <div class="row">
        <div class="col-md-2 col-sm-12 col-xs-12 logo">
          <a href="<%= root_path %>"><%= image_tag("logowhite.png") %></a>
        </div>
        <div class="col-md-10 col-sm-12 col-xs-12 mobile-menu">
          <div class="main-menu">
            <a class="rs-menu-toggle"><i class="fa fa-bars"></i>Menu</a>
            <nav class="rs-menu">
              <ul class="nav-menu">
                <li>
                  <a href="<%= root_path %>">Home</a>
                </li>
                <li>
                  <a href="<%= about_us_path %>">About us</a>
                </li>
                <li>
                  <a href="<%= how_to_bet_path %>">How to bet</a>
                </li>
                <li>
                  <a href="<%= top_100_path %>">Top 100</a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/admin_layout.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Admin WCCoin</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png.html">

    <!-- Place favicon.ico in the root directory -->
    <link rel="shortcut icon" type="image/x-icon" href="images/fav.png">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    <%= stylesheet_link_tag 'application', "styles", media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>
  </head>
  <body class="home-two" >

    <!--Header area start here-->

    <%= render '/layouts/admin_header' %>
    <!--Header area end here-->

    <%= yield %>
    <!-- Footer Start -->
    <!-- Footer End -->



    <!-- Start scrollUp  -->
    <div id="return-to-top">
      <span>Top</span>
    </div>
    <!-- End scrollUp  -->
  </body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>WCCoin</title>
    
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png.html">

    <!-- Place favicon.ico in the root directory -->
    <link rel="shortcut icon" type="image/x-icon" href="images/fav.png">   

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <style>
    </style>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>
  </head>
  <body class="home-two">
        
    <!--Header area start here-->
    <%= render '/layouts/header' %>
    <!--Header area end here-->
    <%= yield %>
    <!-- Footer Start -->
    <%= render '/layouts/footer' %>
    <!-- Footer End -->
        
        
        
    <!-- Start scrollUp  -->
    <div id="return-to-top">
      <span>Top</span>
    </div>
    <!-- End scrollUp  -->

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>